
# Books CRUD
# Should GET all registed books in the API. 
GET localhost:8000/books/all HTTP/1.1

# Should GET one Book given an available ID.
GET localhost:8000/books/1 HTTP/1.1

# Should Add a Book given their Name, ISBN, Author and Uniqueness.
POST localhost:8000/books/all HTTP/1.1
content-type: application/json
{
    "name": "Alfredo de Andrade, O Cavaleiro",
    "isbn": "123-456-789-00",
}

# Should Delete a Book given an existing Id.
DELETE localhost:8000/books/1 HTTP/1.1